"""
install_startup.py — Register SwitchLang to run at Windows logon.

Places a .bat launcher in the user's Startup folder so the app starts
automatically when the user logs in. No admin rights required.
pythonw.exe is used so no console window appears.

Run once from the project root:
    python scripts/install_startup.py

To remove:
    python scripts/install_startup.py --uninstall
"""

import os
import sys

TASK_NAME   = "SwitchLang"
PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VENV_PYTHON = os.path.join(PROJECT_DIR, '.venv', 'Scripts', 'pythonw.exe')
MAIN_PY     = os.path.join(PROJECT_DIR, 'main.py')

# Standard per-user Startup folder (no admin needed)
STARTUP_DIR = os.path.join(
    os.environ.get('APPDATA', ''),
    r'Microsoft\Windows\Start Menu\Programs\Startup'
)
BAT_PATH = os.path.join(STARTUP_DIR, f'{TASK_NAME}.bat')


BAT_CONTENT = f"""@echo off
REM SwitchLang auto-start launcher
REM Generated by install_startup.py — do not edit manually.
cd /d "{PROJECT_DIR}"
start "" "{VENV_PYTHON}" "{MAIN_PY}"
"""


def install():
    if not os.path.isfile(VENV_PYTHON):
        print(f'ERROR: pythonw.exe not found at:\n  {VENV_PYTHON}')
        sys.exit(1)

    if not os.path.isfile(MAIN_PY):
        print(f'ERROR: main.py not found at:\n  {MAIN_PY}')
        sys.exit(1)

    os.makedirs(STARTUP_DIR, exist_ok=True)

    with open(BAT_PATH, 'w', encoding='utf-8') as f:
        f.write(BAT_CONTENT)

    print(f'Startup launcher written to:')
    print(f'  {BAT_PATH}')
    print(f'\nSwitchLang will start automatically at next logon.')
    print(f'To remove: python scripts/install_startup.py --uninstall')


def uninstall():
    if not os.path.isfile(BAT_PATH):
        print(f'Launcher not found — nothing to remove.')
        print(f'  (looked at: {BAT_PATH})')
        return

    os.remove(BAT_PATH)
    print(f'Removed: {BAT_PATH}')
    print(f'SwitchLang will no longer start at logon.')


if __name__ == '__main__':
    if '--uninstall' in sys.argv:
        uninstall()
    else:
        install()
